apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hetznercloud/csi-driver.git
    path: deploy/kubernetes
    targetRevision: v2.16.0 # Use a specific, stable version
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
