apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      terminationGracePeriodSeconds: 60 # Allow up to 60 seconds for graceful shutdown
      containers:
      - name: django
        image: your-docker-image/django-app:latest
        securityContext:
          runAsUser: 1000 # The UID for the appuser
          runAsGroup: 1000 # The GID for the appuser
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: django-secrets # For your other secrets
        - secretRef:
            name: postgres-db-superuser # For the database connection
        - configMapRef:
            name: django-config
        env:
        - name: DATABASE_URL
          value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST)/$(POSTGRES_DB)"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /healthz  # Replace with your actual health check endpoint
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz # Replace with your actual health check endpoint
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
