apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - hpa.yaml
  - ingress.yaml
  - pdb.yaml
  - service.yaml
  - static-deployment.yaml
  - static-pdb.yaml
  - static-service.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: your-docker-image/django-app:latest # Replace with your image
    target:
      kind: Deployment
      name: django-app
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: your-domain.com # Replace with your domain
      - op: replace
        path: /spec/tls/0/hosts/0
        value: your-domain.com # Replace with your domain
    target:
      kind: Ingress
      name: django-ingress
