apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: django-secrets
  namespace: default # Make sure this is the correct namespace for your app
spec:
  encryptedData:
    # This is placeholder data. You will replace this with the output
    # of the 'kubeseal' command.
    SECRET_KEY: AgBy3i4OJSWK+Imx_our_long_encrypted_string_goes_here
    ALLOWED_HOSTS: AgBy3i4OJSWK+Imx_another_long_encrypted_string_goes_here
  template:
    metadata:
      name: django-secrets
      namespace: default # Make sure this is the correct namespace for your app
    type: Opaque
