apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: django-network-policy
spec:
  podSelector:
    matchLabels:
      app: django
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow incoming traffic from the Nginx Ingress Controller
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow traffic to Redis within the cluster
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  # Allow traffic to PostgreSQL within the cluster
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgres-db
    ports:
    - protocol: TCP
      port: 5432
  # Allow traffic to the public internet (for services like Brevo)
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
