apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - pdb.yaml

images:
  - name: your-docker-image/django-app
    newName: your-docker-image/django-app
    newTag: latest
