apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: celery-beat
spec:
  serviceName: "celery-beat"
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: ((your-docker-image/django-app:latest))
        securityContext:
          runAsUser: 1000 # The UID for the appuser
          runAsGroup: 1000 # The GID for the appuser
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command: ["celery", "-A", "$(CELERY_APP_NAME)", "beat", "-l", "info"]
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
