apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-backup-credentials
  namespace: default # Or your preferred application namespace
spec:
  encryptedData:
    # Create a secret with these keys and then encrypt it with kubeseal
    # kubectl create secret generic postgres-backup-credentials \
    #   --from-literal=AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY \
    #   --from-literal=AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY \
    #   --dry-run=client -o yaml | kubeseal --format yaml > backup-credentials-sealed.yaml
    AWS_ACCESS_KEY_ID: AgA...
    AWS_SECRET_ACCESS_KEY: AgA...