---
- name: Install k3s
  shell: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable=traefik --disable=servicelb --node-external-ip={{ hostvars[inventory_hostname]['ansible_host'] }} --kube-apiserver-arg=--cloud-provider=external"

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0644
