---
- name: Install k3s
  shell: "curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644 --disable=traefik --disable=servicelb --node-ip={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} --node-external-ip={{ hostvars[inventory_hostname]['ansible_host'] }} --flannel-iface=eth1 --kube-apiserver-arg=--cloud-provider=external"

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: 0644

- name: Install System Upgrade Controller
  shell: "kubectl apply -f https://github.com/rancher/system-upgrade-controller/releases/download/v0.13.4/system-upgrade-controller.yaml"

- name: Copy upgrade plan
  copy:
    src: upgrade_plan.yaml
    dest: /root/upgrade_plan.yaml
    owner: root
    group: root
    mode: 0644

- name: Apply upgrade plan
  shell: "kubectl apply -f /root/upgrade_plan.yaml"
