apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
data:
  oauth2-proxy.cfg: |-
    provider = "google"
    email_domains = [ "((your-domain.com))" ]
    upstreams = [ "static://200" ]
    cookie_secure = "true"
    cookie_secret = "${COOKIE_SECRET}"
    client_id = "${CLIENT_ID}"
    client_secret = "${CLIENT_SECRET}"
