apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: your-docker-image/django-app:latest
        command: ["celery", "-A", "your_project_name", "worker", "-l", "info"]
        envFrom:
        - secretRef:
            name: django-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - your_project_name
            - status
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - your_project_name
            - status
          initialDelaySeconds: 120
          periodSeconds: 60
