apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      nodeSelector:
        "pool": "small-static"
      containers:
      - name: celery-worker
        image: ((your-docker-image/django-app:latest))
        securityContext:
          runAsUser: 1000 # The UID for the appuser
          runAsGroup: 1000 # The GID for the appuser
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command: ["celery", "-A", "$(CELERY_APP_NAME)", "worker", "-l", "info"]
        envFrom:
        - secretRef:
            name: django-secrets
        - configMapRef:
            name: django-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - $(CELERY_APP_NAME)
            - status
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - $(CELERY_APP_NAME)
            - status
          initialDelaySeconds: 120
          periodSeconds: 60
