apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - static-deployment.yaml
  - static-pdb.yaml
  - static-service.yaml

images:
  - name: your-docker-image/nginx-static
    newName: your-docker-image/nginx-static
    newTag: latest
