apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: prometheus-stack
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - receiver: 'email-notifications'
        match:
          severity: critical
    receivers:
    - name: 'null'
    - name: 'email-notifications'
      email_configs:
      - to: 'YOUR_RECIPIENT_EMAIL@example.com'
        from: 'YOUR_SENDER_EMAIL@your-domain.com'
        smarthost: 'YOUR_SMTP_SERVER:587'
        auth_username: 'YOUR_SENDER_EMAIL@your-domain.com'
        auth_identity: 'YOUR_SENDER_EMAIL@your-domain.com'
        auth_password:
          name: alertmanager-smtp-password
          key: password