apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - custom-alerts.yaml
  - alertmanager-config.yaml
  - grafana-ingress.yaml
  - prometheus-ingress.yaml
  - alertmanager-ingress.yaml
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 75.9.0
    releaseName: kube-prometheus-stack
    namespace: monitoring
    valuesFile: values.yaml
