name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Django image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Dockerfile.django
          platforms: linux/amd64,linux/arm64
          push: true
          tags: your-docker-hub-username/django-app:${{ github.sha }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Dockerfile.nginx
          platforms: linux/amd64,linux/arm64
          push: true
          tags: your-docker-hub-username/nginx-static:${{ github.sha }}
